branches:
    only: master
os: linux
language: python
python:
- 3.7
- 3.6
- 3.8

install: pip install -r requirements/requirements-dev.txt
script: python setup.py $SETUP_CMD
env: SETUP_CMD='test'
before_script: if [[ $SETUP_CMD == *test* ]] || [[ $SETUP_CMD == build_docs ]]; then python setup.py install && python ci/setup_dbase.py; fi

jobs:
  include:
    - env: SETUP_CMD='install'
    - env: SETUP_CMD='test --coverage'
        after_success: coveralls --rcfile='fiasco/tests/coveragerc'
    - os: osx
    - env: SETUP_CMD='test --pep8'
    - env: SETUP_CMD='build_docs'
  allow_failures:
    - env: SETUP_CMD='test --pep8'

stages:
- name: install
- name: test
- name: docs